import { db } from '../../../lib/firebase'
import {
  collection,
  doc,
  getDoc,
  getDocs,
  query,
  where,
  setDoc,
  updateDoc,
  deleteDoc,
  serverTimestamp,
  type Timestamp,
} from 'firebase/firestore'
import { FIRESTORE_COLLECTIONS, type Service } from '../../booking/types'

/**
 * Raw shape of a Service document as received from Firestore.
 * Timestamp fields are converted to Date by fromFirestore().
 */
export interface ServiceDocument
  extends Omit<Service, 'createdAt'> {
  createdAt: Timestamp
}

/**
 * A stable, user-friendly error for service-management failures.
 * Mirrors the BookingError pattern used by the booking module so the admin UI
 * never surfaces raw Firebase errors.
 */
export class ServiceError extends Error {
  readonly code: 'NOT_FOUND' | 'IN_USE' | 'UNKNOWN'

  constructor(code: ServiceError['code'], message: string) {
    super(message)
    this.name = 'ServiceError'
    this.code = code
  }
}

/** Maps an unknown error to a ServiceError with a stable code. */
export function toServiceError(error: unknown): ServiceError {
  if (error instanceof ServiceError) return error
  const message = error instanceof Error ? error.message : undefined
  return new ServiceError(
    'UNKNOWN',
    message ?? 'Something went wrong while managing services. Please try again.',
  )
}

/** Converts raw Firestore Timestamps to JavaScript Date objects. */
function fromFirestore(data: ServiceDocument): Service {
  return {
    ...data,
    createdAt: data.createdAt.toDate(),
  }
}

/**
 * Sort services by sortOrder ascending, then name ascending (case-insensitive).
 * This ordering is the canonical presentation order for the admin module and is
 * kept in the service layer so every consumer stays consistent.
 */
function sortServices(services: Service[]): Service[] {
  return [...services].sort((a, b) => {
    if (a.sortOrder !== b.sortOrder) return a.sortOrder - b.sortOrder
    return a.name.localeCompare(b.name, undefined, { sensitivity: 'base' })
  })
}

/**
 * Fetch all services (active and archived), ordered by sortOrder ASC then name ASC.
 */
export async function getServices(): Promise<Service[]> {
  const snap = await getDocs(collection(db, FIRESTORE_COLLECTIONS.SERVICES))
  const services = snap.docs.map((d) =>
    fromFirestore(d.data() as ServiceDocument),
  )
  return sortServices(services)
}

/**
 * Fetch a single service by its Firestore document ID.
 * Returns null if no service exists with that ID.
 */
export async function getService(serviceId: string): Promise<Service | null> {
  const ref = doc(db, FIRESTORE_COLLECTIONS.SERVICES, serviceId)
  const snap = await getDoc(ref)
  if (!snap.exists()) return null
  return fromFirestore(snap.data() as ServiceDocument)
}

/** Payload used to create a new service document. */
export interface CreateServicePayload {
  name: string
  category: Service['category']
  durationMinutes: number
  priceFrom: number
  description?: string
  sortOrder: number
  isActive: boolean
}

/**
 * Create a new service. The document ID is auto-generated by Firestore so the
 * salon owner does not need to think about stable slugs. `createdAt` is always
 * server-set to prevent client clock manipulation.
 *
 * @returns The new Firestore document ID.
 */
export async function createService(
  payload: CreateServicePayload,
): Promise<string> {
  const ref = doc(collection(db, FIRESTORE_COLLECTIONS.SERVICES))
  await setDoc(ref, {
    serviceId: ref.id,
    name: payload.name,
    category: payload.category,
    durationMinutes: payload.durationMinutes,
    priceFrom: payload.priceFrom,
    description: payload.description ?? '',
    sortOrder: payload.sortOrder,
    isActive: payload.isActive,
    createdAt: serverTimestamp(),
  })
  return ref.id
}

/** Payload used to update an existing service. */
export interface UpdateServicePayload {
  name: string
  category: Service['category']
  durationMinutes: number
  priceFrom: number
  description?: string
  sortOrder: number
  isActive: boolean
}

/**
 * Update an existing service's editable fields.
 * `updatedAt` is server-set. Throws ServiceError('NOT_FOUND') if the document
 * does not exist so the caller can surface a clear message.
 */
export async function updateService(
  serviceId: string,
  payload: UpdateServicePayload,
): Promise<void> {
  const ref = doc(db, FIRESTORE_COLLECTIONS.SERVICES, serviceId)
  const snap = await getDoc(ref)
  if (!snap.exists()) {
    throw new ServiceError(
      'NOT_FOUND',
      'This service no longer exists. It may have been deleted.',
    )
  }
  await updateDoc(ref, {
    name: payload.name,
    category: payload.category,
    durationMinutes: payload.durationMinutes,
    priceFrom: payload.priceFrom,
    description: payload.description ?? '',
    sortOrder: payload.sortOrder,
    isActive: payload.isActive,
    updatedAt: serverTimestamp(),
  })
}

/**
 * Archive a service (isActive = false).
 * Archived services disappear from the customer booking wizard immediately
 * because the wizard only queries services with isActive == true.
 */
export async function archiveService(serviceId: string): Promise<void> {
  await updateDoc(doc(db, FIRESTORE_COLLECTIONS.SERVICES, serviceId), {
    isActive: false,
    updatedAt: serverTimestamp(),
  })
}

/** Restore a previously archived service (isActive = true). */
export async function restoreService(serviceId: string): Promise<void> {
  await updateDoc(doc(db, FIRESTORE_COLLECTIONS.SERVICES, serviceId), {
    isActive: true,
    updatedAt: serverTimestamp(),
  })
}

/**
 * Count how many bookings reference this service. Used by the UI to protect
 * against destructive deletes: services with historical bookings should be
 * archived, never hard-deleted.
 */
export async function getServiceUsageCount(serviceId: string): Promise<number> {
  const q = query(
    collection(db, FIRESTORE_COLLECTIONS.BOOKINGS),
    where('serviceId', '==', serviceId),
  )
  const snap = await getDocs(q)
  return snap.size
}

/**
 * Permanently delete a service. Only permitted by the caller when
 * `getServiceUsageCount` returned 0 — hard-deleting a referenced service would
 * orphan historical bookings. The UI always prefers archive over delete.
 */
export async function deleteService(serviceId: string): Promise<void> {
  await deleteDoc(doc(db, FIRESTORE_COLLECTIONS.SERVICES, serviceId))
}

